### ISSUE TITLE
There's something wrong with page.summary in 1.3.3 when use Chinese

### ISSUE THREAD

**Issue by dimlau** [getgrav/grav#1657]
{{ post.summary(60)|striptags }}

Display like this:

![2017-09-20 6 24 10](https://user-images.githubusercontent.com/396423/30639517-ca99dfee-9e31-11e7-83f1-a5ebbce38011.png)

Of course the characters at the end is unwanted.

**Comment by rhukster** [comment]
This is probably because the character count was in the middle of a tag or something.  Can you try another 'value' rather than 60?

**Comment by rhukster** [comment]
OH actually this might well be fixed with latest develop version. There's a fix that is not in the current release: https://github.com/getgrav/grav/commit/79fa88c31586d2d43643ab4505e076a55b2d4585

**Comment by dimlau** [comment]
I copy the new page.php file, and this time I use {{ page.summary }} ( I set the value of summary size '90' in admin panel...

But seems that's not work:

![2017-09-23 7 54 11](https://user-images.githubusercontent.com/396423/30773032-a6e653a0-a09a-11e7-9de4-49f8944bb4f5.png)
 
Still see the strange characters, like 'ǻ'...

**Comment by rhukster** [comment]
can you provide a copy of your actual page markdown so i can try and test with your exact UTF-8 based content?

**Comment by dimlau** [comment]
Here is one of my post.md file, hope this helps

[post.md.zip](https://github.com/getgrav/grav/files/1327031/post.md.zip)
