### ISSUE TITLE
Base_url_absolute always has the port number

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav#1690]
Hi!

Not sure if it is on purpose, but now base_url_absolute always have the portnumber.
I also used to use: `$this->grav['uri']->base()` but it now displays the port number too.

The only way to have an url without it would be to make it like this:
```
$this->grav['uri']->scheme() . $this->grav['uri']->host();
```

Thanks!

Paul

**Comment by rhukster** [comment]
My nderstsnding is that if the port is non standard it should display.  Else not. 

@mahagr did fix a bug related to this, but maybe it’s not fixed entirely?

**Comment by w00fz** [comment]
Yeah 80 and 443 shouldn’t be really showing as they are implicit.

**Comment by paulmassen** [comment]
age standard port 443 and 80? 

cant say for 80 but 443 is displayed on all my install

**Comment by paulmassen** [comment]
Looks like it therefore breaks all image which use absolute urls, which prevent sharing with opengraph or twitter metadata.

**Comment by rhukster** [comment]
@mahagr is going to look at it as both djamil and myself are traveling today.

**Comment by mahagr** [comment]
It looks like Uri::init() line 264 does this.

**Comment by mahagr** [comment]
Should be fixed now. The issue was caused by code being moved around, looks like I forgot to add the default port check into the new location.

**Comment by fucx** [comment]
I'm having the same issue, on my server `$_SERVER['HTTPS']` is on, but `$_SERVER['SERVER_PORT']` is 80. So the check in `hasStandardPort()` returns `false` and the port 80 gets added to the URI.
`force_ssl` is `true` in my system.yaml.

**Comment by mahagr** [comment]
@fucx What happens if you turn force ssl off?

**Comment by fucx** [comment]
Then it doesn't include the port number any more. I could still force TLS through the .htaccess, I suppose?

**Comment by fucx** [comment]
But in the sitemap (through the plugin with the same name), the port numbers still get included.

**Comment by mahagr** [comment]
This is because of 80 isn't the default port for https.

**Comment by fucx** [comment]
Which is why the links don't work, since the server isn't serving HTTPS from port 80.

**Comment by mahagr** [comment]
Yes, it looks like a bug. I'll check it out.

**Comment by mahagr** [comment]
Is this still issue for you as I've not been able to reproduce the issue.

**Comment by Blazeflack** [comment]
I found this ticket as I was searching for an issue I had. It turns out this ticket describes my issue entirely.

I have set up a website for a client in my workplace, which is hosted at one.com. When the website is served over https then canonical tags and any other tag which uses absolute paths includes the port number 80 in the URL. If you want to take a look then you can do so at frankinstituteofsports.com.

I currently have force_ssl set to false, but it was previously set to true. Neither setting fixes this issue.

I contacted one.com about this, because I have not experienced this issue on any of the other instances of Grav we have set up on the host UnoEuro. The engineers from one.com gave me the following response:

>We have received updates from our Technical team and confirmed that the plugin tinyseo is generating the meta tags where the value of SERVER_PORT is 80, even if actual URL is working over HTTPS and using the port 443.

>You can either fix the PHP script user/plugins/tinyseo/tinyseo.php to use PORT 443 on HTTPS connection, or you can use the following to fix SERVER PORT detection on HTTPS:

```
if(isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO']=='https') {
$_SERVER['SERVER_PORT'] = 443;
}
```

I think they misunderstood the role of the tiny seo plugin. While it is true it generates some meta tags, it is not responsible for generating the URL itself as it uses Grav functions to do so ( url(true) ).

If you need me to perform tests of any kind to help you narrow down the issue then please let me know. I am very eager to have this fixed so I can properly enforce SSL on the domain.

Thank you.

**Comment by mahagr** [comment]
Closing due to inactivity and the fact that @Blazeflack told that his issue had already been fixed in #1827

**Comment by poopsplat** [comment]
I appear to be having the same issue as @fucx with my site that is also has `$_SERVER['HTTPS']` on

**Comment by poopsplat** [comment]
I appear to be having the same issue as @fucx with my site that also uses HTTPS, running Grav v1.5.4

**Comment by rhukster** [comment]
Pretty sure this is fixed in 1.6 beta? Can you guys please test that?
