### ISSUE TITLE
Grav 1.7-rc2, once Grav 1.6 is updated to RC2 error on Plugins Page in Admin

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2753]
I've been trying to test RC2 in all of my skeletons, but I seem to be getting an error after I update Grav to RC2 (which works) and then go to the Plugins Page in Admin to update the needed Plugins:

<img width="1200" alt="2019-12-06_07-40-26" src="https://user-images.githubusercontent.com/1812771/70335202-b3dc2280-17fb-11ea-8aa4-c7a3cb59108f.png">

The front-end of the site works fine.

Here is the entry in the Grav log:
```
[2019-12-06 07:37:26] grav.CRITICAL: array_key_exists() expects parameter 2 to be array, null given - Trace: #0 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Debugger.php(787): Whoops\Run->handleError(2, 'array_key_exist...', '/Users/paulhibb...', 722) #1 [internal function]: Grav\Common\Debugger->deprecatedErrorHandler(2, 'array_key_exist...', '/Users/paulhibb...', 722, Array) #2 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Page/Pages.php(722): array_key_exists('', NULL) #3 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Page/Page.php(2324): Grav\Common\Page\Pages->get('') #4 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Page/Page.php(1841): Grav\Common\Page\Page->parent() #5 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Page/Page.php(1808): Grav\Common\Page\Page->route() #6 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Page/Page.php(193): Grav\Common\Page\Page->url() #7 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Service/PagesServiceProvider.php(93): Grav\Common\Page\Page->init(Object(SplFileInfo)) #8 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\PagesServiceProvider::Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #9 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/user/plugins/presentation/presentation.php(489): Pimple\Container->offsetGet('page') #10 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\PresentationPlugin->onAdminPagesAssetsInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #11 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #12 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'onAssetsInitial...', Object(RocketTheme\Toolbox\Event\Event)) #13 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Grav.php(422): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(RocketTheme\Toolbox\Event\Event), 'onAssetsInitial...') #14 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/AssetsProcessor.php(27): Grav\Common\Grav->fireEvent('onAssetsInitial...') #15 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #16 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #17 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/SchedulerProcessor.php(31): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #18 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #19 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #20 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/BackupsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #21 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #22 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #23 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/TasksProcessor.php(60): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #24 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #25 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #26 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/RequestProcessor.php(54): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #27 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #28 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #29 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/ThemesProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #30 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #31 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #32 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/PluginsProcessor.php(32): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #33 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #34 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #35 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/InitializeProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #36 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Debugger.php(529): Grav\Common\Processors\InitializeProcessor->Grav\Common\Processors\{closure}() #37 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/InitializeProcessor.php(70): Grav\Common\Debugger->profile(Object(Closure)) #38 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #39 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #40 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Grav.php(227): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #41 /Users/paulhibbitts/Documents/My Files/GitHub/_RC/grav-skeleton-open-matter-course-hub-site/index.php(56): Grav\Common\Grav->process() #42 {main} [] []
```

Please let me know if any additional information is helpful.

Thanks very much,
Paul

**Comment by mahagr** [comment]
@paulhibbitts Check my fix and try it out. :)

**Comment by paulhibbitts** [comment]
Thanks very much @mahagr , but the issue still seems to be there?

I updated my local test install with this commit:
https://github.com/getgrav/grav/commit/185e9b52724f902c8806ed9306339c3ca551bdf0

Did I miss something?

**Comment by mahagr** [comment]
It should fix the issue as the `$instances` cannot be anything else but array after that.

**Comment by paulhibbitts** [comment]
Let me try to test things again @mahagr ...

**Comment by paulhibbitts** [comment]
Awesome @mahagr , that worked! I must have made a mix-up with my first test, thanks very much!

**Comment by MakaryGo** [comment]
@mahagr any chance to push it to GPM? As for now after update to RC2 via command line it's still broken :)
