### ISSUE TITLE
Enable autoescape in new sites, keep the current setting in old

### ISSUE THREAD

**Issue by mahagr** [getgrav/grav#3069]
Starting from Grav 1.7, Grav will change the default setting:

```yaml
twig:
  autoescape: true
```

Some logic will be added to ensure that the old setting will be kept in the existing sites, though even those should be tested and updated to work with auto-escape on. The feature is already forced to be on in admin and will be enforced in Grav 2.0.

The auto-escape feature improves site security by preventing most of the potential XSS attacks without template designer needing to manually escape every single variable. If you have not been writing all your Twig like this: `{{ variable|e }}`, this change is especially good for you. Having auto-escape on in your projects will help you to write better code.

For existing sites, it is recommended to make a local test site and turn the `autoescape` setting on in there. This is because of if you haven't been paying attention on which content to escape and which not, your twig will likely be missing some `|raw` filters to display safe HTML content. In this case, the resulting markup will be escaped and shown as HTML code in your site. These issues are generally rare and easy to fix but do require some testing.

**Comment by NicoHood** [comment]
I am currently playing around with autoescape and I have a few questions.

When do we actually WANT escaping? I can only think of two scenarios:
* For data entered by the admin plugin, like page content
* For use input coming from forms/plugins (like the comment plugin)

### About the first, page content:
I am not sure if that is really a good idea or even possible with markdown. But what if you have a site where users have access to a few pages. I think that should be possible with 1.7 now. How can you ensure their content can have markdown formatted text, but no XSS is possible?

### About the second, user input from plugins:
I am currently facing the following issue:
* User input from forms already removes html tags, meaning it should be safe (is it?)
* Some characters like `"` are stored as `&#34;`. This means if a user enters an input like `<script>echo("hello there!");<script>` It becomes `echo("hello there!"); ` with autoescape OFF and `echo(&#34;hello there!&#34;);` with autoescape ON.

So wouldnt it make more sense to add `|striptags|raw` instead of `|e` in that case? Maybe that could be also handled in the autoescape engine to still render those html codes `&#34;`?

**Comment by mahagr** [comment]
IMHO everything should always be escaped. The only exception is when you know that the content is safe HTML (or javascript / HTML attribute). So basically only when you're generating the content yourself inside the template file.

This means that even translations should be escaped and they should never contain any HTML, such as links. In practice, this may not always be possible because of it may be more convenient to have those links inside the translation, but that also raises questions if translations should be considered to be safe (IMHO they are not). It is better to not to escape the few known HTML translations, though, and keep everything else escaped than to allow all translations to go through without escaping them.

What comes to `|safe_email`, it looks to me to be a bug. It should make sure that the email address is valid and return safe HTML, which allows you to skip `|raw` filter with it.

**Comment by NicoHood** [comment]
> So basically only when you're generating the content yourself inside the template file.

How can I add the option for users to edit pages with markdown, but still escape additional html tags?

> This means that even translations should be escaped and they should never contain any HTML

Alright, I aggree.

> What comes to |safe_email, it looks to me to be a bug. 

I am also using `safe_html` for obfuscating phone numbers and the address in the impress, not only email. I found that feature very helpful, so if you fix anything, please keep that in mind.

**Comment by NicoHood** [comment]
I am not sure if it is possible, but can the translate function be extended to support something like this:
```
{{ 'PLUGIN_RATINGS.EMAIL_MESSAGE'|t(('<b><a href="' ~ base_url_absolute ~ '">' ~ site.title|e ~ '</a></b>')|raw)|e }}

EMAIL_MESSAGE: "Thank you very much for your rating on the website %s.
```

This way we could inject safe links (or anything else) to a translatable strings. However I am not sure if that is technically possible, as the filter maybe cannot be applied to the printf format string only without escaping `%s` as well? Any ideas?

**Comment by NicoHood** [comment]
I found another issue:

How can I use `grav['twig']->processTemplate()` without escaping? For example:
```php
// Check if json_ld should be added to page
if ($settings->get('add_json_ld', $add_json_ld)) {
    // Generate json-ld
    $json_ld = $this->grav['twig']->processTemplate(
      $template,
      [
        'data' => $data,
        'page' => $page,
        'settings' => $settings
      ]);

    $this->grav['assets']->addInlineJs($json_ld, ['type' => 'application/ld+json']);
}
```

This will escape all my json to html, but it MUST be pure json in order for google to recognize it properly.

**Comment by mahagr** [comment]
Translating already supports parameters, so it's pretty easy to move links outside of the language strings -- and some already are.

It's not a bad idea to have `|safe_text` or similar filter. I'm also considering `|html` filter, which is similar to `|raw` but filters out unsafe HTML.

**Comment by NicoHood** [comment]
> Translating already supports parameters, so it's pretty easy to move links outside of the language strings -- and some already are.

That is what I try to explain: It does not work (or at least I think so, check the example above)

**Comment by mahagr** [comment]
Fixed `|safe_email` filter, you can basically pass anything into it and it'll encode it as text.

**Comment by NicoHood** [comment]
I am confused, maybe I am missing something. Can we please go more into detail here?

The language.yaml
```
PLUGIN_RATINGS:
  EMAIL_MESSAGE: "Thank you very much for your rating on the website %s.
```

The html.twig
```
{{ 'PLUGIN_RATINGS.EMAIL_MESSAGE'|t(('<b><a href="' ~ base_url_absolute ~ '">' ~ site.title|e ~ '</a></b>')|raw)|e }}
```

Will be rendered as html (some characters might come from email):
```
Thank you very much for your rating on the website &lt;b&gt;&lt;a href=&quot;http://localhost:8000&quot;&gt;NicoHoods Blog&lt;/a&gt;&lt;/b&gt;.
```

Visible to the user:
```
Thank you very much for your rating on the website <b><a href="http://localhost:8000">NicoHoods Blog</a></b>.
```

So **escaping translations does not work with parameters.** Or at least parameter will always be escaped which will make the example above impossible. Do you have a solution for this?


Btw: I like the idea of having `safe_text`, it could be an alias of `safe_email` for now.

**Comment by w00fz** [comment]
Don’t do |e, if you know you want raw html you need just |raw

**Comment by NicoHood** [comment]
@w00fz Yes, that is exactly the problem!

> IMHO everything should always be escaped. [...] This means that even translations should be escaped and they should never contain any HTML, such as links.

So we cannot have a safe/escaped translation here. Also in some cases it does not make sense to put the link around the translation part, as it would split the template too much (that is the reason why translation parameters were introduced). So to me this is still an issue.

**Comment by w00fz** [comment]
It’s not an issue. The translation will just always automatically escape. Meaning that if you have html in your translation it will be escaped. Unless you translate in twig files with raw to allow for html.

Nothing really is changing here. All it’s happening is we are swapping the default auto escape setting grav always came in with. Instead of being off by default, it will be on. Instead of writing simple `{{ variable }}` that auto render html, now you have to be conscious about it and write `{{ variable|raw }}` instead.

### Before 1.7
Writing `{{ variable }}` was equivalent to `{{ variable|raw }}`

### After 1.7 (only on new sites, never if you are just updating from 1.6)
Writing `{{ variable }}` was equivalent to `{{ variable|e }}`

**Comment by NicoHood** [comment]
Sure, I understand that. But when @mahagr says translations should be escaped always (for security, etc.) it does not make sense to exclude some translations and some not.

**Comment by w00fz** [comment]
He also says in practice this is not always possible because sometimes you do want your HTML in your language strings and there's nothing wrong with that. This is why by default they will now be escaped always but if we are aware of a language that might contain HTML we will render it `|raw` or, whenever this is available, as `|html`

**Comment by NicoHood** [comment]
Alright, thanks for clarifying :-)

**Comment by mahagr** [comment]
Yeah, sorry about the misconfusion. What I meant to say was that most language strings do not contain HTML and should as such be escaped (no HTML allowed as afterthought). And if you have links, you should move the links outside the translation to a parameter -- I didn't mean removing the markup in that case, though.

Here's an example: `Thank you very much for your rating on the website <b><a href="%s">%s</a></b>.`

Of course in that case you need to remember to explicitly escape your parameters to be safe.
