### ISSUE TITLE
getFormFieldTypes() does not merge settings

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3219]
Imagine a plugin code like this:
```php
    /** @var array */
    public $features = [
        'formfields' => 0
    ];

    /**
     * Get list of form field types specified in this plugin.
     * Only special types needs to be listed.
     * NOTE: This function gets called by the grav plugin framework.
     *
     * @return array
     */
    public function getFormFieldTypes()
    {
        return [
            'rating' => [
                'validate' => [
                    'type' => 'number',
                    'step' => 1,
                    'min' => 1,
                    'max' => 5
                ]
            ]
        ];
    }
```

Now I got the following yaml file:
```yaml
        - name: stars
          type: rating
          label: PLUGIN_RATINGS.RATING_LABEL
          validate:
            required: true
```

Because I specified `validate.required: true` all other settings set by `getFormFieldTypes()` are now lost. I need to repeat them again, which is more error prone:

```yaml
        - name: stars
          type: rating
          label: PLUGIN_RATINGS.RATING_LABEL
          validate:
            min: 1
            max: 5
            step: 1
            type: number
            required: true
```

**Comment by mahagr** [comment]
Yes, that is kind of what is expected as it's not a merge, but just adding missing keys (defaults) to the main level. In most cases merging would be wrong anyway, but I think that for validate it should do an exception.

**Comment by mahagr** [comment]
Needs a fix in `vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php` line 509 and 514.

**Comment by mahagr** [comment]
Should be fixed in toolbox.

**Comment by NicoHood** [comment]
What is the target milestone/version?

**Comment by mahagr** [comment]
Next version, it'll be out today.

**Comment by NicoHood** [comment]
This still does not work for me with 1.7.12. And yes, I've done a composer update.

**Comment by mahagr** [comment]
I tested adding the field into a page.

I'm getting this error when trying to enter invalid value:
```
Invalid input in "PLUGIN_RATINGS.RATING_LABEL"
Save Failed: Form validation failed, please check your input
```

So the validation surely works, at least in admin and with flex objects.

**Comment by NicoHood** [comment]
Seems not to be the case for frontend forms. I am using this form field template to test (i've manually modified the max to 10, but the code should limit it to 5)

```twig
{% extends "forms/field.html.twig" %}

{% set originalValue = value %}

{% block input %}
    <fieldset class="rating-input {{ form_field_wrapper_classes }} {{ field.wrapper_classes }}">
        {# It is important to count from max to min, as this is required by the css. #}
        {% for i in 10..field.validate.min|default(1) %}
            {% set id = field.id|default(field.name) ~ '-star' ~ i %}
            <input type="radio"
                   value="{{ i|e }}"
                   id="{{ id|e }}"
                   name="{{ (scope ~ field.name)|fieldName }}"
                   class="{{ form_field_rating_classes }} {{ field.classes }}"
                   {% if i == value %}checked="checked" {% endif %}
                   {% if field.disabled or isDisabledToggleable %}disabled="disabled"{% endif %}
                   {% if required %}required="required"{% endif %}
                   {% if field.tabindex %}tabindex="{{ field.tabindex }}"{% endif %}
                   min="{{ field.validate.min|default(1) }}"
                   max="{{ field.validate.max|default(5) }}"
                   step="{{ field.validate.step|default(1) }}"
            />
            <label for="{{ id|e }}" title="{{ field.titles[i]|t|default(i ~ ' ' ~ 'PLUGIN_RATINGS.STARS'|t) }}"></label>
        {% endfor %}
    </fieldset>

{% endblock %}
```

**Comment by mahagr** [comment]
I reopened the issue so I won't forget it.
